import { Button } from "@/components/ui/button";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <header className="flex justify-between gap-4 items-center px-4 py-2 border-b">
        <span className="text-xl font-semibold">LOGO</span>

        <div className="flex gap-4 items-center">
          <Button variant="outline"> Registrati </Button>
          <Button> Accedi </Button>
        </div>
      </header>

      <main className="p-4">{children}</main>
    </div>
  );
}
